# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-02 16:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_auto_20160502_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.FileField(default=datetime.datetime(2016, 5, 2, 16, 51, 14, 783000, tzinfo=utc), upload_to=b''),
            preserve_default=False,
        ),
    ]
