# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-14 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_blogpost_order1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='order1',
        ),
    ]
