# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-07 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_auto_20160507_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
