# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-07 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_auto_20160507_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
