# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-07 05:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_auto_20160507_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.FileField(default=datetime.datetime(2016, 5, 7, 5, 39, 12, 548000, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
