# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-07 12:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0007_auto_20160507_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='posted_by',
            field=models.CharField(default=datetime.datetime(2016, 5, 7, 12, 38, 33, 982000, tzinfo=utc), max_length=150),
            preserve_default=False,
        ),
    ]
