# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-14 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0008_blogpost_posted_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
